project_id = "zlaqrczybwsifhbpakun"

[functions.mp-webhook]
verify_jwt = false

[functions.mp-payment-status]
verify_jwt = false

[functions.mp-create-preference]
verify_jwt = false

[functions.mp-refund]
verify_jwt = false

[functions.mapbox-token]
verify_jwt = false

[functions.firebase-config]
verify_jwt = false